version: 2

jobs:
  image-tests-mpl202:
    docker:
      - image: astropy/image-tests-py35-mpl202:1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install .[test]
      - run:
          name: Run tests
          command: tox -e py35-test -- --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpl212:
    docker:
      - image: astropy/image-tests-py35-mpl212:1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install .[test]
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpl222:
    docker:
      - image: astropy/image-tests-py35-mpl222:1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install .[test]
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpl300:
    docker:
      - image: astropy/image-tests-py35-mpl300:1.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip3 install .[test]
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov
  image-tests-mpldev:
    docker:
      - image: astropy/image-tests-py36-base:1.1
    steps:
      - checkout
      - run:
          name: Install apt dependencies
          command: apt-get install -y libfreetype6-dev libpng12-dev pkg-config
      - run:
          name: Install dependencies
          command: pip3 install .[test] git+https://github.com/matplotlib/matplotlib.git
      - run:
          name: Run tests
          command: MPLBACKEND=Agg pytest --remote-data=any --mpl
      - run:
          name: Report coverage
          command: codecov


workflows:
  version: 2
  build_and_test:
    jobs:
      - image-tests-mpl202
      - image-tests-mpl212
      - image-tests-mpl222
      - image-tests-mpl300
      - image-tests-mpldev
